// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYGuBcvHYUX_fY9v0ev2cKrXVXb3cJmvQ',
    appId: '1:659906351102:web:04be575501b12ae6a8faaf',
    messagingSenderId: '659906351102',
    projectId: 'fir-auth-1da5e',
    authDomain: 'fir-auth-1da5e.firebaseapp.com',
    storageBucket: 'fir-auth-1da5e.appspot.com',
    measurementId: 'G-W0J5FJBBB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2MlPCz_MWLZaXLG2vIgL8XXUGlIMsG7M',
    appId: '1:659906351102:android:70b9a4b04f5faa38a8faaf',
    messagingSenderId: '659906351102',
    projectId: 'fir-auth-1da5e',
    storageBucket: 'fir-auth-1da5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6AZRuN68iVTs3f6JIj3mAKI0t3ts1oec',
    appId: '1:659906351102:ios:bf5e0fec29da8118a8faaf',
    messagingSenderId: '659906351102',
    projectId: 'fir-auth-1da5e',
    storageBucket: 'fir-auth-1da5e.appspot.com',
    androidClientId: '659906351102-ic50hs4ktn69nnf3jb8fndalu674hsrv.apps.googleusercontent.com',
    iosClientId: '659906351102-cte9689k79askiv7drqrjh0mh3hq2i92.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6AZRuN68iVTs3f6JIj3mAKI0t3ts1oec',
    appId: '1:659906351102:ios:bf5e0fec29da8118a8faaf',
    messagingSenderId: '659906351102',
    projectId: 'fir-auth-1da5e',
    storageBucket: 'fir-auth-1da5e.appspot.com',
    androidClientId: '659906351102-ic50hs4ktn69nnf3jb8fndalu674hsrv.apps.googleusercontent.com',
    iosClientId: '659906351102-cte9689k79askiv7drqrjh0mh3hq2i92.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireAuth',
  );
}
