/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData chat_bubble = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData droplet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wb_sunny = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach_access = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_giftcard = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_list_bulleted = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData footprint = IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knife_fork = IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xf005, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_1 = IconData(0xf01d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones = IconData(0xf025, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf = IconData(0xf06c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xf06d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xf0b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blank = IconData(0xf0c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xf0c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xf0eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope = IconData(0xf0f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad = IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal = IconData(0xf1a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = IconData(0xf1b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xf1b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday_cake = IconData(0xf1fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship = IconData(0xf21a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_start = IconData(0xf251, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData television = IconData(0xf26c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin = IconData(0xf276, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fort_awesome = IconData(0xf286, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xf290, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xf291, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_order = IconData(0xf2b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book = IconData(0xf2b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowflake = IconData(0xf2dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docker = IconData(0xf395, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freebsd = IconData(0xf3a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itunes_note = IconData(0xf3b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_alt = IconData(0xf3d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData studiovinari = IconData(0xf3f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball_ball = IconData(0xf433, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball_ball = IconData(0xf434, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess = IconData(0xf439, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_ball = IconData(0xf44e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball_ball = IconData(0xf45f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills = IconData(0xf484, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_open = IconData(0xf49e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_astronaut = IconData(0xf4fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open = IconData(0xf518, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frog = IconData(0xf52e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helicopter = IconData(0xf533, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kiwi_bird = IconData(0xf535, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_check_alt = IconData(0xf53d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xf549, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walking = IconData(0xf554, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xf555, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drafting_compass = IconData(0xf568, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xf578, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_martini_alt = IconData(0xf57b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin_stars = IconData(0xf587, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marked_alt = IconData(0xf5a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marker = IconData(0xf5a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_ruler = IconData(0xf5ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spa = IconData(0xf5bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tooth = IconData(0xf5c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_alt = IconData(0xf5d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain = IconData(0xf5dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shapes = IconData(0xf61f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_of_life = IconData(0xf621, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xf64f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pastafarianism = IconData(0xf67b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData synagogue = IconData(0xf69b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torii_gate = IconData(0xf6a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xf6be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chair = IconData(0xf6c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d6 = IconData(0xf6d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragon = IconData(0xf6d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost = IconData(0xf6e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData canadian_maple_leaf = IconData(0xf785, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carrot = IconData(0xf787, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xf7d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xf805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza_slice = IconData(0xf818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons = IconData(0xf86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
